# Generated by Django 4.1.4 on 2023-07-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0002_dat"),
    ]

    operations = [
        migrations.AddField(
            model_name="dat",
            name="comment",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
