# Generated by Django 4.1.4 on 2023-07-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0003_dat_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="meaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cl", models.CharField(blank=True, max_length=44, null=True)),
            ],
        ),
    ]
