# Generated by Django 4.1.4 on 2023-07-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0006_user_groups_user_is_superuser_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=55, unique=True),
        ),
    ]
