# Generated by Django 4.1.4 on 2023-07-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0009_passwords_delete_dat_delete_meaw"),
    ]

    operations = [
        migrations.RenameField(
            model_name="passwords",
            old_name="notes",
            new_name="name",
        ),
        migrations.AddField(
            model_name="passwords",
            name="passwd",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
