# Generated by Django 4.1.4 on 2023-07-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0010_rename_notes_passwords_name_passwords_passwd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwords",
            name="owner",
            field=models.IntegerField(),
        ),
    ]
