# Generated by Django 4.1.4 on 2023-06-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="snipet",
            old_name="lineos",
            new_name="linenos",
        ),
    ]
