# Generated by Django 4.1.4 on 2023-06-24 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theapp", "0002_rename_lineos_snipet_linenos"),
    ]

    operations = [
        migrations.RenameField(
            model_name="snipet",
            old_name="linenos",
            new_name="linen",
        ),
    ]
