# Generated by Django 4.1.4 on 2023-06-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theapp", "0003_rename_linenos_snipet_linen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snipet",
            name="linen",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
