# Generated by Django 4.1.4 on 2023-06-24 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theapp", "0004_alter_snipet_linen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snipet",
            name="linen",
        ),
    ]
